services:
  - type: web
    name: telegram-nutrition-bot
    env: python
    region: singapore
    plan: free
    buildCommand: ""
    startCommand: "gunicorn -w 1 -b 0.0.0.0:10000 main:app"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
